### ISSUE TITLE
The difference between part1 and part2 in 161010_Chinese_Spring_v1.0_pseudomolecules_parts.fasta 

### ISSUE THREAD

**Issue by sip123a** [hcph/wheat_singlecellAtlas#1]
Thank you for sharing a single cell diagram analysis code. I have a question to ask, what is the relationship between chr1a_part1 and chr1a_part2? Is it a homologous chromosome?

The following is the length information of the sequence.Thanks again.

chr1A_part1     471304005 
chr1A_part2     122798051 
chr1B_part1     438720154 
chr1B_part2     251131716 
chr1D_part1     452179604 
chr1D_part2     43273582  
chr2A_part1     462376173 
chr2A_part2     318422384 
chr2B_part1     453218924 
chr2B_part2     348037791 
chr2D_part1     462216879 
chr2D_part2     189635730 
chr3A_part1     454103970 
chr3A_part2     296739669 
chr3B_part1     448155269 
chr3B_part2     382674495 
chr3D_part1     476235359 
chr3D_part2     139317064 
chr4A_part1     452555092 
chr4A_part2     292033065 
chr4B_part1     451014251 
chr4B_part2     222603248 
chr4D_part1     451004620 
chr4D_part2     58852447  
chr5A_part1     453230519 
chr5A_part2     256543224 
chr5B_part1     451372872 
chr5B_part2     261776885 
chr5D_part1     451901030 
chr5D_part2     114179647 
chr6A_part1     452440856 
chr6A_part2     165638404 
chr6B_part1     452077197 
chr6B_part2     268911281 
chr6D_part1     450509124 
chr6D_part2     23083594  
chr7A_part1     450046986 
chr7A_part2     286659250 
chr7B_part1     453822637 
chr7B_part2     296797748 
chr7D_part1     453812268 
chr7D_part2     184873787

**Comment by hcph** [comment]
Thank you for your interest in our work. When aligning with the STAR software, the chromosome length cannot exceed 530M. However, each wheat chromosome exceeds this length. Therefore, it was necessary to divide the chromosome into two parts. Chr1A_part1 and Chr1A_part2 represent the division of Chr1A into two parts, which were obtained from the IWGSC official website.
